// Layer types
export const TYPE_COPPER = 'copper'
export const TYPE_SOLDERMASK = 'soldermask'
export const TYPE_SILKSCREEN = 'silkscreen'
export const TYPE_SOLDERPASTE = 'solderpaste'
export const TYPE_DRILL = 'drill'
export const TYPE_OUTLINE = 'outline'
export const TYPE_DRAWING = 'drawing'

// Board sides
export const SIDE_TOP = 'top'
export const SIDE_BOTTOM = 'bottom'
export const SIDE_INNER = 'inner'
export const SIDE_ALL = 'all'

// Cad packages
// internal use only, for now
export const CAD_KICAD = 'kicad'
export const CAD_ALTIUM = 'altium'
export const CAD_ALLEGRO = 'allegro'
export const CAD_EAGLE = 'eagle'
export const CAD_EAGLE_LEGACY = 'eagle-legacy'
export const CAD_EAGLE_OSHPARK = 'eagle-oshpark'
export const CAD_EAGLE_PCBNG = 'eagle-pcbng'
export const CAD_GEDA_PCB = 'geda-pcb'
export const CAD_ORCAD = 'orcad'
export const CAD_DIPTRACE = 'diptrace'
export const CAD_PROTEUS = 'proteus'
export const CAD_PADS = 'pads'
export const CAD_CIRCUITMAKER = 'circuitmaker'
export const CAD_EASYEDA = 'easyeda'
export const CAD_CADENCE_ALLEGRO = 'cadence-allegro'
export const CAD_TARGET_3001 = 'target-3001'
export const CAD_PCAD = 'pcad'
export const CAD_XPEDITION = 'xpedition'
export const CAD_GEDA = 'geda'
export const CAD_PCB123 = 'pcb123'
export const CAD_ULTIBOARD = 'ultiboard'
export const CAD_CIRCUITSTUDIO = 'circuitstudio'
export const CAD_FRITZING = 'fritzing'
export const CAD_MULTISIM = 'multisim'
export const CAD_EXPEESSPCB = 'expresspcb'
export const CAD_ZENITPCB = 'zenitpcb'
export const CAD_TINKERCAD = 'tinkercad'
export const CAD_AUTODESK_EAGLE = 'autodesk-eagle'
export const CAD_DESIGNSPARK_PCB = 'designspark-pcb'
export const CAD_TINA = 'tina'
export const CAD_EASY_PC = 'easy-pc'
export const CAD_SPRINT_LAYOUT = 'sprint-layout'

