import {
  TYPE_COPPER,
  TYPE_SOLDERMASK,
  TYPE_SILKSCREEN,
  TYPE_SOLDERPASTE,
  TYPE_DRILL,
  TYPE_OUTLINE,
  TYPE_DRAWING,
  SIDE_TOP,
  SIDE_BOTTOM,
  SIDE_INNER,
  SIDE_ALL,
  TYPE_REPORT,
  CAD_KICAD,
  CAD_ALTIUM,
  CAD_ALLEGRO,
  CAD_EAGLE,
  CAD_EAGLE_LEGACY,
  CAD_EAGLE_OSHPARK,
  CAD_EAGLE_PCBNG,
  CAD_GEDA_PCB,
  CAD_ORCAD,
  CAD_DIPTRACE,
  CAD_PROTEUS,
  CAD_CADENCE_ALLEGRO,
  CAD_CIRCUITMAKER,
  CAD_EASYEDA,
  CAD_PADS,
  CAD_TARGET_3001,
  CAD_PCAD,
  CAD_GEDA,
  CAD_PCB123,
  CAD_XPEDITION,
  CAD_AUTODESK_EAGLE,
  CAD_CIRCUITSTUDIO,
  CAD_EXPEESSPCB,
  CAD_FRITZING,
  CAD_MULTISIM,
  CAD_TINKERCAD,
  CAD_ULTIBOARD,
  CAD_ZENITPCB,
  CAD_DESIGNSPARK_PCB,
  CAD_EASY_PC,
  CAD_TINA,
  CAD_SPRINT_LAYOUT,
  CAD_GERBV,
  CAD_VIEWMATE,
  CAD_GERBERLOGIX,
  CAD_ZOFZPCB,
  CAD_CAM350,
  CAD_OSMOND_PCB,
  CAD_UCAMCO
} from './constants'

import type {LayerType} from './types'

export const layerTypes: LayerType[] = [
  // High-priority non-matches
  {
    type: null,
    side: null,
    matchers: [
      // Eagle gerber generation metadata
      {
        ext: 'gpi',
        cad: [CAD_EAGLE, CAD_EAGLE_LEGACY, CAD_EAGLE_OSHPARK, CAD_EAGLE_PCBNG],
      },
      // Eagle drill generation metadata
      {
        ext: 'dri',
        cad: [CAD_EAGLE, CAD_EAGLE_LEGACY, CAD_EAGLE_OSHPARK, CAD_EAGLE_PCBNG],
      },
      // General data/BOM files
      {ext: 'csv', cad: null},
      // Pick-n-place BOMs
      {match: /pnp_bom/, cad: CAD_EAGLE_PCBNG},
    ],
  },
  {
    type: TYPE_COPPER,
    side: SIDE_TOP,
    matchers: [
      {ext: 'cmp', cad: CAD_EAGLE_LEGACY},
      {ext: 'top', cad: [CAD_EAGLE_LEGACY, CAD_ORCAD, CAD_CADENCE_ALLEGRO, CAD_XPEDITION, CAD_DIPTRACE]},
      {ext: 'gtl', cad: [CAD_KICAD, CAD_ALTIUM, CAD_DIPTRACE, CAD_CIRCUITMAKER, CAD_PROTEUS, CAD_PADS, CAD_EASYEDA, CAD_TARGET_3001, CAD_PCAD, CAD_GEDA, CAD_PCB123, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_EXPEESSPCB, CAD_ZENITPCB, CAD_TINKERCAD, CAD_AUTODESK_EAGLE, CAD_DESIGNSPARK_PCB, CAD_EASY_PC, CAD_TINA, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB ]},
      {ext: 'toplayer\\.ger', cad: CAD_EAGLE_OSHPARK},
      {match: /top\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /f[._]cu/, cad: CAD_KICAD},
      {match: /copper_top/, cad: CAD_EAGLE},
      {match: /top_copper/, cad: CAD_EAGLE_PCBNG},
      {match: /top copper/, cad: null},
    ],
  },
  {
    type: TYPE_SOLDERMASK,
    side: SIDE_TOP,
    matchers: [
      {ext: 'stc', cad: CAD_EAGLE_LEGACY},
      {ext: 'tsm', cad: CAD_EAGLE_LEGACY},
      {ext: 'gts', cad: [CAD_KICAD, CAD_ALTIUM, CAD_PROTEUS, CAD_DIPTRACE, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_GEDA, CAD_PCB123, CAD_DIPTRACE, CAD_TINA, CAD_PCB123, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB ]},
      {ext: 'smt', cad: [CAD_ORCAD, CAD_PADS, CAD_CADENCE_ALLEGRO, CAD_XPEDITION, CAD_EXPEESSPCB]},
      {ext: 'smk', cad: [CAD_ORCAD]},
      {ext: 'stc', cad: [CAD_DIPTRACE]},
      {ext: 'topsoldermask\\.ger', cad: CAD_EAGLE_OSHPARK},
      {match: /topmask\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /f[._]mask/, cad: CAD_KICAD},
      {match: /soldermask_top/, cad: CAD_EAGLE},
      {match: /top_mask/, cad: CAD_EAGLE_PCBNG},
      {match: /top solder resist/, cad: null},
    ],
  },
  {
    type: TYPE_SILKSCREEN,
    side: SIDE_TOP,
    matchers: [
      {ext: 'plc', cad: [CAD_EAGLE_LEGACY, CAD_DIPTRACE]},
      {ext: 'tsk', cad: CAD_EAGLE_LEGACY},
      {ext: 'gto', cad: [CAD_KICAD, CAD_ALTIUM, CAD_PROTEUS, CAD_DIPTRACE, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_GEDA, CAD_PCB123, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_EXPEESSPCB, CAD_ZENITPCB, CAD_TINKERCAD, CAD_AUTODESK_EAGLE, CAD_PCB123, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB ]},
      {ext: 'sst', cad: [CAD_ORCAD, CAD_PADS, CAD_CADENCE_ALLEGRO, CAD_XPEDITION, CAD_EXPEESSPCB]},
      {ext: 'plt', cad: CAD_ORCAD},
      {ext: 'topsilkscreen\\.ger', cad: CAD_EAGLE_OSHPARK},
      {match: /topsilk\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /f[._]silks/, cad: CAD_KICAD},
      {match: /silkscreen_top/, cad: CAD_EAGLE},
      {match: /top_silk/, cad: CAD_EAGLE_PCBNG},
      {match: /top silk screen/, cad: null},
    ],
  },
  {
    type: TYPE_SOLDERPASTE,
    side: SIDE_TOP,
    matchers: [
      {ext: 'crc', cad: CAD_EAGLE_LEGACY},
      {ext: 'tsp', cad: CAD_EAGLE_LEGACY},
      {ext: 'gtp', cad: [CAD_KICAD, CAD_ALTIUM, CAD_PROTEUS, CAD_DIPTRACE, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_GEDA, CAD_PCB123, CAD_ULTIBOARD,CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]},
      {ext: 'spt', cad: CAD_ORCAD},
      {ext: 'spk', cad: CAD_ORCAD},
      {ext: 'sps', cad: CAD_DIPTRACE},
      {ext: 'tcream\\.ger', cad: CAD_EAGLE_OSHPARK},
      {match: /toppaste\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /f[._]paste/, cad: CAD_KICAD},
      {match: /solderpaste_top/, cad: CAD_EAGLE},
      {match: /top_paste/, cad: CAD_EAGLE_PCBNG},
    ],
  },
  {
    type: TYPE_COPPER,
    side: SIDE_BOTTOM,
    matchers: [
      {ext: 'sol', cad: CAD_EAGLE_LEGACY},
      {ext: 'bot', cad: [CAD_EAGLE_LEGACY, CAD_ORCAD, CAD_DIPTRACE]},
      {ext: 'gbl', cad: [CAD_KICAD, CAD_ALTIUM, CAD_PROTEUS, CAD_DIPTRACE, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_GEDA, CAD_PCB123, CAD_ULTIBOARD,CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]},
      {ext: 'bottomlayer\\.ger', cad: CAD_EAGLE_OSHPARK},
      {match: /bottom\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /b[._]cu/, cad: CAD_KICAD},
      {match: /copper_bottom/, cad: CAD_EAGLE},
      {match: /bottom_copper/, cad: CAD_EAGLE_PCBNG},
      {match: /bottom copper/, cad: null},
    ],
  },
  {
    type: TYPE_SOLDERMASK,
    side: SIDE_BOTTOM,
    matchers: [
      {ext: 'sts', cad: [CAD_EAGLE_LEGACY, CAD_DIPTRACE]},
      {ext: 'bsm', cad: CAD_EAGLE_LEGACY},
      {ext: 'gbs', cad: [CAD_KICAD, CAD_ALTIUM, CAD_PROTEUS, CAD_DIPTRACE, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_GEDA, CAD_PCB123, CAD_ULTIBOARD,CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]},
      {ext: 'smb', cad: [CAD_ORCAD, CAD_PADS, CAD_CADENCE_ALLEGRO, CAD_XPEDITION, CAD_EXPEESSPCB]},
      {ext: 'bottomsoldermask\\.ger', cad: CAD_EAGLE_OSHPARK},
      {match: /bottommask\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /b[._]mask/, cad: CAD_KICAD},
      {match: /soldermask_bottom/, cad: CAD_EAGLE},
      {match: /bottom_mask/, cad: CAD_EAGLE_PCBNG},
      {match: /bottom solder resist/, cad: null},
    ],
  },
  {
    type: TYPE_SILKSCREEN,
    side: SIDE_BOTTOM,
    matchers: [
      {ext: 'pls', cad: [CAD_EAGLE_LEGACY, CAD_DIPTRACE]},
      {ext: 'bsk', cad: CAD_EAGLE_LEGACY},
      {ext: 'gbo', cad: [CAD_KICAD, CAD_ALTIUM, CAD_PROTEUS, CAD_DIPTRACE, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_GEDA, CAD_PCB123, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]},
      {ext: 'ssb', cad: [CAD_ORCAD, CAD_PADS, CAD_CADENCE_ALLEGRO, CAD_XPEDITION, CAD_EXPEESSPCB]},
      {ext: 'bottomsilkscreen\\.ger', cad: CAD_EAGLE_OSHPARK},
      {ext: 'plb', cad: CAD_ORCAD},
      {match: /bottomsilk\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /b[._]silks/, cad: CAD_KICAD},
      {match: /silkscreen_bottom/, cad: CAD_EAGLE},
      {match: /bottom_silk/, cad: CAD_EAGLE_PCBNG},
      {match: /bottom silk screen/, cad: null},
    ],
  },
  {
    type: TYPE_SOLDERPASTE,
    side: SIDE_BOTTOM,
    matchers: [
      {ext: 'crs', cad: CAD_EAGLE_LEGACY},
      {ext: 'bsp', cad: CAD_EAGLE_LEGACY},
      {ext: 'gbp', cad: [CAD_KICAD, CAD_ALTIUM]},
      {ext: 'spb', cad: CAD_ORCAD},
      {ext: 'sps', cad: CAD_DIPTRACE},
      {ext: 'bcream\\.ger', cad: CAD_EAGLE_OSHPARK},
      {match: /bottompaste\.\w+$/, cad: [CAD_GEDA_PCB, CAD_DIPTRACE]},
      {match: /b[._]paste/, cad: CAD_KICAD},
      {match: /solderpaste_bottom/, cad: CAD_EAGLE},
      {match: /bottom_paste/, cad: CAD_EAGLE_PCBNG},
    ],
  },
  {
    type: TYPE_COPPER,
    side: SIDE_INNER,
    matchers: [
      {ext: 'ly\\d+', cad: CAD_EAGLE_LEGACY},
      {ext: 'gp?\\d+', cad: [CAD_KICAD, CAD_ALTIUM]},
      {ext: 'in\\d+', cad: CAD_ORCAD},
      {ext: 'internalplane\\d+\\.ger', cad: CAD_EAGLE_OSHPARK},
      {ext: 'g\\d+', cad: [CAD_CAM350]},
      {match: /in(?:ner)?\d+[._]cu/, cad: CAD_KICAD},
      {match: /inner/, cad: CAD_DIPTRACE},
    ],
  },
  {
    type: TYPE_OUTLINE,
    side: SIDE_ALL,
    matchers: [
      {ext: 'dim', cad: CAD_EAGLE_LEGACY},
      {ext: 'mil', cad: CAD_EAGLE_LEGACY},
      {ext: 'gml', cad: CAD_EAGLE_LEGACY},
      {ext: 'gm\\d+', cad: [CAD_KICAD, CAD_ALTIUM, CAD_ORCAD]},
      {ext: 'gko', cad: CAD_ALTIUM},
      {ext: 'fab', cad: CAD_ORCAD},
      //{ext: 'drd', cad: CAD_ORCAD},
      {match: /outline/, cad: [CAD_GEDA_PCB, CAD_EAGLE_PCBNG]},
      {match: /boardoutline/, cad: [CAD_EAGLE_OSHPARK, CAD_DIPTRACE]},
      {match: /edge[._]cuts/, cad: CAD_KICAD},
      {match: /profile/, cad: CAD_EAGLE},
      {match: /mechanical \d+/, cad: null},
    ],
  },
  {
    type: TYPE_DRILL,
    side: SIDE_ALL,
    matchers: [
      {ext: 'txt', cad: [CAD_EAGLE_LEGACY, CAD_ALTIUM, CAD_EASYEDA, CAD_AUTODESK_EAGLE]},
      {
        ext: 'xln',
        cad: [CAD_EAGLE, CAD_EAGLE_LEGACY, CAD_EAGLE_OSHPARK],
      },
      {ext: 'exc', cad: CAD_EAGLE_LEGACY},
      {ext: 'drd', cad: [CAD_EAGLE_LEGACY, CAD_ORCAD]},
      {ext: 'drl', cad: [CAD_KICAD, CAD_DIPTRACE, CAD_ALTIUM, CAD_ORCAD, CAD_PROTEUS, CAD_PADS, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_CADENCE_ALLEGRO, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_XPEDITION, CAD_GEDA, CAD_PCB123, CAD_SPRINT_LAYOUT, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_EXPEESSPCB, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]},
      {ext: 'tap', cad: CAD_ORCAD},
      {ext: 'npt', cad: CAD_ORCAD},
      {ext: 'plated-drill\\.cnc', cad: CAD_GEDA_PCB},
      {match: /fab/, cad: CAD_GEDA_PCB},
      {match: /npth/, cad: CAD_KICAD},
      {match: /drill/, cad: CAD_EAGLE_PCBNG},
    ],
  },
  {
    type: TYPE_DRAWING,
    side: null,
    matchers: [
      {ext: 'cam', cad: CAD_AUTODESK_EAGLE},
      {ext: 'pos', cad: CAD_KICAD},
      {ext: 'art', cad: [CAD_KICAD, CAD_DIPTRACE, CAD_ALTIUM, CAD_ORCAD, CAD_PROTEUS, CAD_PADS, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_CADENCE_ALLEGRO, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_XPEDITION, CAD_GEDA, CAD_PCB123, CAD_SPRINT_LAYOUT, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_EXPEESSPCB, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]},
      {ext: 'gbr', cad: [CAD_KICAD, CAD_DIPTRACE, CAD_ALTIUM, CAD_ORCAD, CAD_PROTEUS, CAD_PADS, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_CADENCE_ALLEGRO, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_XPEDITION, CAD_GEDA, CAD_PCB123, CAD_SPRINT_LAYOUT, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_EXPEESSPCB, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]},
      {ext: 'gbx', cad: null},
      {ext: 'ger', cad: null},
      {ext: 'pho', cad: null},
    ],
  },
  {
    type: TYPE_REPORT,
    side: null,
    matchers: [
      {ext: 'rep', cad: [CAD_KICAD, CAD_DIPTRACE, CAD_ALTIUM, CAD_ORCAD, CAD_PROTEUS, CAD_PADS, CAD_CIRCUITMAKER, CAD_DESIGNSPARK_PCB, CAD_EASYEDA, CAD_CADENCE_ALLEGRO, CAD_TARGET_3001, CAD_TINA, CAD_EASY_PC, CAD_PCAD, CAD_XPEDITION, CAD_GEDA, CAD_PCB123, CAD_SPRINT_LAYOUT, CAD_ULTIBOARD, CAD_CIRCUITSTUDIO, CAD_FRITZING, CAD_MULTISIM, CAD_EXPEESSPCB, CAD_TINKERCAD, CAD_GERBV, CAD_VIEWMATE, CAD_GERBERLOGIX, CAD_ZOFZPCB, CAD_CAM350, CAD_OSMOND_PCB]}
    ],
  }
]
